---
- hosts: all
  become: true
  tasks:
    - name: Install ZSH, Git...
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - zsh
          - git
          # - net-tools
