---
# ansible-galaxy install gantsign.oh-my-zsh
- hosts: all
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: vagrant
      oh_my_zsh_plugins:
        - git
        - microk8s
        - kubectl
